AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'

Metrics/LineLength:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
