language: ruby
rvm:
  - 2.3.1
env:
  - RAILS_ENV=test
services:
  - postgresql
addons:
  postgresql: "9.4"
bundler_args: --jobs=3 --retry=3 --deployment --without development production
before_script:
  - psql -c 'create database rails_starter_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - bundle exec spring rspec spec
notifications:
  slack: rails-starter-app:tGN9IXmnlXewbhVtpG2I9vrY
