language: ruby
rvm:
  - 2.3.1
env:
  - RAILS_ENV=test
services:
  - postgresql
addons:
  postgresql: "9.4"
bundler_args: --jobs=3 --retry=3 --deployment --without development production
before_script:
  - psql -c 'create database rails_starter_test;' -U postgres
script:
  - bundle exec spring rspec spec
